### ISSUE TITLE
Peer dependency issue via @vue-macros/nuxt

### ISSUE THREAD

**Issue by nathanchase** [sxzz/unplugin-combine#40]
### Describe the bug

In my Nuxt 3 project, I have the following warning:
```
 WARN  Issues with peer dependencies found
└─┬ @vue-macros/nuxt 1.3.8
  └─┬ unplugin-vue-macros 2.1.7
    └─┬ unplugin-combine 0.6.0
      └── ✕ unmet peer rollup@^3.2.0: found 2.79.1 in workbox-build
```
If I remove `@vue-macros/nuxt` - the warning goes away.

My `.npmrc` looks like this:
```
use-node-version=18.15.0
engine-strict=true
auto-install-peers=true
shamefully-hoist=true
```
It's unclear if it's `unplugin-combine` that has the issue, or something else up the chain, but thought I'd mention it here in case there's a dependency issue that can be resolved. I did try to create a reproduction StackBlitz, but I'm not seeing the same behavior there. It could be due to the limitations of StackBlitz - but I'm not sure...

### Reproduction

https://stackblitz.com/edit/github-jki4wp?file=package.json

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 19.73 GB / 23.44 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
It's just a warning, not an error. In your case, it won't break anything. pnpm will fix this.
